server:
  port: 8189
  servlet:
    context-path: /security
spring:
  jpa:
    show-sql: true
    hibernate:
#      dialect: org.hibernate.dialect.H2Dialect
      ddl-auto: update
#      temp:
#        use_jdbc_metadata_defaults: false
  datasource:
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/springsecurity
    username: root
    password: kObOx_326
  flyway:
    enabled: false
#    driver-class-name: org.postgresql.Driver
#    url: jdbc:postgresql://localhost:5432/postgres?currentSchema=sec
#    username: postgres
#    password: admin
